name: hello-world-demo
on:
  push:
    branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: execute demo script
        run: |
            chmod +x demo.sh
            ./demo.sh
    
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: test deploy
        run: |
            echo "Deploying the application..." 
            date
            df -kh
  scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: test scan
        run: |
            echo "Running security scan..." 
            date
            